### ISSUE TITLE
fix link to FreeSWITCH/Verto Installation Guide on tut/installing-verto.html

### ISSUE THREAD

**Issue by thehunmonkgroup** [EvoluxBR/verto-docs#14]
the 'FreeSWITCH/Verto Installation Guide' link on the installing verto page points to a deprecated page, where should we point it instead?

perhaps to Tristan Mahe's installation script, https://github.com/thehunmonkgroup/freeswitch-kickstart, or someplace that describes how to install FS via packages?

**Comment by victor-torres** [comment]
You can link one of these installation scripts, but I think we should add something more detailed like a how-to. 

The Installation guide on Confluence will be deprecated? Is there another newer link? They won’t maintain any documentation in installing FS anymore?

**Comment by italorossi** [comment]
Couldn't find this page, but all the info related on installing verto communicator should be in https://freeswitch.org/confluence/display/FREESWITCH/Verto+Communicator .

**Comment by thehunmonkgroup** [comment]
@italorossi the link i'm trying to update is not concerned with installing Verto Communicator, but a base FreeSWITCH/Verto i've updated it to link to https://freeswitch.org/confluence/display/FREESWITCH/mod_verto and https://freeswitch.org/confluence/display/FREESWITCH/Installation, as those seem like the most reasonable wiki docs to accomplish that goal.
