### ISSUE TITLE
add bootstrap.min.css to repo?

### ISSUE THREAD

**Issue by thehunmonkgroup** [EvoluxBR/verto-docs#15]
the code currently points to a CDN for the bootstrap CSS, and while this does reduce the code in the repository a bit, it also introduces an external dependency.

more importantly perhaps, it makes working on the docs without an internet connection a very unpleasant experience :)

my preference would be to commit that file to the repo, thoughts?

**Comment by StefanYohansson** [comment]
Indeed. I will add some love in prebuild process.
maybe we can use any tool **{grunt, gulp, webpack, browserify}** to generate a minified css (including bootstrap).

**Comment by victor-torres** [comment]
@StefanYohansson you can just add the bootstrap.css file to the repository as a quick solution.

**Comment by thehunmonkgroup** [comment]
seems like overkill to minify everything, it's not that complicated to begin with.

i'll just add the bootstrap CSS file to the repo and link to it, as suggested by @victor-torres
