### ISSUE TITLE
Create a script to publish new releases in gh-pages

### ISSUE THREAD

**Issue by victor-torres** [EvoluxBR/verto-docs#17]
Now we’re doing it manually. It basically consists in copying new versions of the files to the gh-pages branch. We should automate this task.

**Comment by thehunmonkgroup** [comment]
i don't know enough about your setup to recommend the best method, but here are all the official deployment recommendations from the Jekyll project: https://jekyllrb.com/docs/deployment-methods/

**Comment by victor-torres** [comment]
We could do something with Travis CI:

https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

**Comment by victor-torres** [comment]
@kalmik take a look here

**Comment by victor-torres** [comment]
Done.

**Comment by italorossi** [comment]
👏

**Comment by thehunmonkgroup** [comment]
am i correct in assuming this script will rebuild on every commit to master?

**Comment by victor-torres** [comment]
Yes @thehunmonkgroup
