### ISSUE TITLE
Check bootstrap grid for menu and content

### ISSUE THREAD

**Issue by StefanYohansson** [EvoluxBR/verto-docs#19]
Menu overflow :stuck_out_tongue: 

![screenshot from 2016-08-23 21-06-19](https://cloud.githubusercontent.com/assets/1783252/17914120/e7333390-6975-11e6-8973-f1b7df060700.png)

**Comment by thehunmonkgroup** [comment]
i just noticed this today, too -- and of course the most important link, 'contributors' isn't visible :P

**Comment by thehunmonkgroup** [comment]
just a note that the fix won't appear on the live site until a rebuild...
