### ISSUE TITLE
Conference control from verto (chat messages) documentation

### ISSUE THREAD

**Issue by vladutz33** [EvoluxBR/verto-docs#28]
Hi guys,
I know that there was a way you could add participants and remove them from the conference using the chat but I cannot find any documentation on the subject, can you help? Also is there a easy way to add/remove conference participant from the interface? Thank you.

**Comment by italorossi** [comment]
Using the chat? I don't remember this feature. And currently, there's no way to add participant from the UI.
There's underlying APIs  for that on mod_conference, like bgdial, dia. You can check the docs here: 
https://freeswitch.org/confluence/display/FREESWITCH/mod_conference#mod_conference-APIReference

And you can set some bindings to add them to the conference using DTMF:
https://freeswitch.org/confluence/display/FREESWITCH/Conference+Add+Call+Example
