### ISSUE TITLE
Conference commands - add new participant

### ISSUE THREAD

**Issue by tudoradridan** [EvoluxBR/verto-docs#29]
Hi,
Do you know if there's a conference command or some other way to add a new participant to conference? Thank you!

**Comment by tudoradridan** [comment]
Hi,
I couldn't find anything in verto. The only workaround I found is to call webapi (mod_xml_rpc) conference command. Thanks!

**Comment by victor-torres** [comment]
Hi, @tudoradridan. So, have you found a workaround? Would you mind submitting a pull request sharing how you solved it?

**Comment by tudoradridan** [comment]
Hello, I've solved this by making an async web get like https://host/webapi/conference?conf-name dial {originate_timeout=30}]user/301@domain. Nothing related to verto.

**Comment by victor-torres** [comment]
Thanks for sharing, @tudoradridan

**Comment by italorossi** [comment]
If the user has moderator flag, there’s an extra API function that you can use to dial to a dialstring:

https://freeswitch.org/confluence/display/FREESWITCH/mod_conference#mod_conference-APIReference

Commands dial and bgdial.

The default implementation of $.verto.conf does not encapsulate those methods, the function responsible for wrapping the underlying API is createMainModeratorMethods at html5/verto/src/jquery.verto.js.

Feel free to submit an issue and a PR at https://freeswitch.org/jira.
